name: "build and deploy"

on: [pull_request]

env:
  AZURE_WEBAPP_NAME: thedevblog
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  NETCORE_VERSION: '3.1.402'

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK ${{ env.NETCORE_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.NETCORE_VERSION }}

    # name: Restore
    #  run: dotnet restore

    #- name: Build
    #  run: dotnet build --no-restore -c Release

    - name: Publish
      run: |
        dotnet build --configuration release
        dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/Dev-Blog/Dev-Blog'

    - name: 'Deploy to Azure'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }} 





